# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FFTRecorder' do
  pod 'STHTTPRequest', '~> 1.1.0'
end

target 'FFTRecorderTests' do

end

